/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apk_fuzzy;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author ASUS
 */
public class proses extends javax.swing.JFrame {

    /**
     * Creates new form proses
     */
    double input1,input2;
    double min1,max1;
    double min2,max2;
    double hsl1,hsl2,hsl3,hsl4;
    ArrayList<Double>min_hsl = new ArrayList();
    
    public proses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar_pnl = new javax.swing.JPanel();
        proses_pnl = new javax.swing.JPanel();
        soal_pnl = new javax.swing.JPanel();
        lbl_input1 = new javax.swing.JLabel();
        lbl_input2 = new javax.swing.JLabel();
        tf_input1 = new javax.swing.JTextField();
        tf_input2 = new javax.swing.JTextField();
        btn_proses = new javax.swing.JButton();
        var_pnl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_data = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_rules = new javax.swing.JTable();
        fuzzifikasi_pnl = new javax.swing.JPanel();
        lbl_f1 = new javax.swing.JLabel();
        tf_f1 = new javax.swing.JTextField();
        tf_f2 = new javax.swing.JTextField();
        lbl_f2 = new javax.swing.JLabel();
        tf_f3 = new javax.swing.JTextField();
        lbl_f3 = new javax.swing.JLabel();
        tf_f4 = new javax.swing.JTextField();
        lbl_f4 = new javax.swing.JLabel();
        btn_grafik = new javax.swing.JButton();
        operasi_pnl = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_operasi = new javax.swing.JTable();
        implikasi_pnl = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tb_implikasi = new javax.swing.JTable();
        komposisi_pnl = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tb_komposisi = new javax.swing.JTable();
        defuzzifikasi_pnl = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        spn_nilai = new javax.swing.JSpinner();
        jScrollPane7 = new javax.swing.JScrollPane();
        tb_defuzifikasi = new javax.swing.JTable();
        centroid_pnl = new javax.swing.JPanel();
        tf_centroid = new javax.swing.JTextField();
        btn_centroid = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar_pnl.setBackground(new java.awt.Color(0, 153, 153));
        navbar_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proses_pnl.setBackground(new java.awt.Color(255, 255, 255));
        proses_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        soal_pnl.setBackground(new java.awt.Color(0, 153, 153));
        soal_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "Soal Crips", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        lbl_input1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_input1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_input1.setText("jLabel2");

        lbl_input2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_input2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_input2.setText("jLabel2");

        tf_input1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_input1KeyTyped(evt);
            }
        });

        tf_input2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_input2KeyTyped(evt);
            }
        });

        btn_proses.setText("Proses");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout soal_pnlLayout = new javax.swing.GroupLayout(soal_pnl);
        soal_pnl.setLayout(soal_pnlLayout);
        soal_pnlLayout.setHorizontalGroup(
            soal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, soal_pnlLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lbl_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_input2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_input2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_proses)
                .addGap(162, 162, 162))
        );
        soal_pnlLayout.setVerticalGroup(
            soal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, soal_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_input1)
                    .addComponent(lbl_input2)
                    .addComponent(btn_proses)
                    .addComponent(tf_input2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        proses_pnl.add(soal_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 940, 70));

        var_pnl.setBackground(new java.awt.Color(0, 153, 153));
        var_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "[0] Fuzzy Init", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tb_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jenis", "Nama Variabel", "Min Variabel", "Min Value", "Max Variabel", "Max Value", "Satuan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tb_data);
        if (tb_data.getColumnModel().getColumnCount() > 0) {
            tb_data.getColumnModel().getColumn(0).setResizable(false);
            tb_data.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_data.getColumnModel().getColumn(1).setResizable(false);
            tb_data.getColumnModel().getColumn(2).setResizable(false);
            tb_data.getColumnModel().getColumn(3).setResizable(false);
            tb_data.getColumnModel().getColumn(4).setResizable(false);
            tb_data.getColumnModel().getColumn(5).setResizable(false);
            tb_data.getColumnModel().getColumn(6).setResizable(false);
        }

        tb_rules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "Sebab", "Akibat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tb_rules);
        if (tb_rules.getColumnModel().getColumnCount() > 0) {
            tb_rules.getColumnModel().getColumn(0).setResizable(false);
            tb_rules.getColumnModel().getColumn(0).setPreferredWidth(70);
            tb_rules.getColumnModel().getColumn(1).setResizable(false);
            tb_rules.getColumnModel().getColumn(1).setPreferredWidth(470);
            tb_rules.getColumnModel().getColumn(2).setResizable(false);
            tb_rules.getColumnModel().getColumn(2).setPreferredWidth(300);
        }

        javax.swing.GroupLayout var_pnlLayout = new javax.swing.GroupLayout(var_pnl);
        var_pnl.setLayout(var_pnlLayout);
        var_pnlLayout.setHorizontalGroup(
            var_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(var_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        var_pnlLayout.setVerticalGroup(
            var_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var_pnlLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        proses_pnl.add(var_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 570, -1));

        fuzzifikasi_pnl.setBackground(new java.awt.Color(0, 153, 153));
        fuzzifikasi_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "[1] Fuzzifikasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        lbl_f1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_f1.setText("jLabel2");

        tf_f1.setEditable(false);

        tf_f2.setEditable(false);

        lbl_f2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_f2.setText("jLabel2");

        tf_f3.setEditable(false);

        lbl_f3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_f3.setText("jLabel2");

        tf_f4.setEditable(false);

        lbl_f4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_f4.setText("jLabel2");

        btn_grafik.setText("Grafik");
        btn_grafik.setEnabled(false);
        btn_grafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grafikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fuzzifikasi_pnlLayout = new javax.swing.GroupLayout(fuzzifikasi_pnl);
        fuzzifikasi_pnl.setLayout(fuzzifikasi_pnlLayout);
        fuzzifikasi_pnlLayout.setHorizontalGroup(
            fuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fuzzifikasi_pnlLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(fuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_grafik)
                    .addGroup(fuzzifikasi_pnlLayout.createSequentialGroup()
                        .addGroup(fuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_f1)
                            .addComponent(tf_f1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(fuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_f2)
                            .addComponent(tf_f2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(fuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_f3)
                            .addComponent(tf_f3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(fuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_f4)
                            .addComponent(tf_f4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        fuzzifikasi_pnlLayout.setVerticalGroup(
            fuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fuzzifikasi_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fuzzifikasi_pnlLayout.createSequentialGroup()
                        .addComponent(lbl_f4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fuzzifikasi_pnlLayout.createSequentialGroup()
                        .addComponent(lbl_f3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fuzzifikasi_pnlLayout.createSequentialGroup()
                        .addComponent(lbl_f2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fuzzifikasi_pnlLayout.createSequentialGroup()
                        .addComponent(lbl_f1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_grafik)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        proses_pnl.add(fuzzifikasi_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 570, 350));

        operasi_pnl.setBackground(new java.awt.Color(0, 153, 153));
        operasi_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "[2] Operasi Fuzzy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tb_operasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rules", "Nilai Minimum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tb_operasi);
        if (tb_operasi.getColumnModel().getColumnCount() > 0) {
            tb_operasi.getColumnModel().getColumn(0).setResizable(false);
            tb_operasi.getColumnModel().getColumn(0).setPreferredWidth(20);
            tb_operasi.getColumnModel().getColumn(0).setHeaderValue("Rules");
            tb_operasi.getColumnModel().getColumn(1).setResizable(false);
            tb_operasi.getColumnModel().getColumn(1).setPreferredWidth(200);
            tb_operasi.getColumnModel().getColumn(1).setHeaderValue("Nilai Minimum");
        }

        javax.swing.GroupLayout operasi_pnlLayout = new javax.swing.GroupLayout(operasi_pnl);
        operasi_pnl.setLayout(operasi_pnlLayout);
        operasi_pnlLayout.setHorizontalGroup(
            operasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(operasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(operasi_pnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        operasi_pnlLayout.setVerticalGroup(
            operasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(operasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(operasi_pnlLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        proses_pnl.add(operasi_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 360, 140));

        implikasi_pnl.setBackground(new java.awt.Color(0, 153, 153));
        implikasi_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "[3] Implikasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tb_implikasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rules", "Nilai Implikasi", "Decision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tb_implikasi);
        if (tb_implikasi.getColumnModel().getColumnCount() > 0) {
            tb_implikasi.getColumnModel().getColumn(0).setResizable(false);
            tb_implikasi.getColumnModel().getColumn(0).setPreferredWidth(40);
            tb_implikasi.getColumnModel().getColumn(1).setResizable(false);
            tb_implikasi.getColumnModel().getColumn(1).setPreferredWidth(120);
            tb_implikasi.getColumnModel().getColumn(2).setResizable(false);
            tb_implikasi.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        javax.swing.GroupLayout implikasi_pnlLayout = new javax.swing.GroupLayout(implikasi_pnl);
        implikasi_pnl.setLayout(implikasi_pnlLayout);
        implikasi_pnlLayout.setHorizontalGroup(
            implikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(implikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(implikasi_pnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        implikasi_pnlLayout.setVerticalGroup(
            implikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(implikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(implikasi_pnlLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        proses_pnl.add(implikasi_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 360, 130));

        komposisi_pnl.setBackground(new java.awt.Color(0, 153, 153));
        komposisi_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "[4] Komposisi Aturan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tb_komposisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(tb_komposisi);

        javax.swing.GroupLayout komposisi_pnlLayout = new javax.swing.GroupLayout(komposisi_pnl);
        komposisi_pnl.setLayout(komposisi_pnlLayout);
        komposisi_pnlLayout.setHorizontalGroup(
            komposisi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(komposisi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(komposisi_pnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        komposisi_pnlLayout.setVerticalGroup(
            komposisi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
            .addGroup(komposisi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(komposisi_pnlLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        proses_pnl.add(komposisi_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 360, 80));

        defuzzifikasi_pnl.setBackground(new java.awt.Color(0, 153, 153));
        defuzzifikasi_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "[5] Defuzzifikasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Nilai Random");

        btn_ok.setText("OK");
        btn_ok.setEnabled(false);
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(tb_defuzifikasi);

        javax.swing.GroupLayout defuzzifikasi_pnlLayout = new javax.swing.GroupLayout(defuzzifikasi_pnl);
        defuzzifikasi_pnl.setLayout(defuzzifikasi_pnlLayout);
        defuzzifikasi_pnlLayout.setHorizontalGroup(
            defuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defuzzifikasi_pnlLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ok)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(defuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(defuzzifikasi_pnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        defuzzifikasi_pnlLayout.setVerticalGroup(
            defuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defuzzifikasi_pnlLayout.createSequentialGroup()
                .addGroup(defuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spn_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ok))
                .addGap(0, 103, Short.MAX_VALUE))
            .addGroup(defuzzifikasi_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(defuzzifikasi_pnlLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        proses_pnl.add(defuzzifikasi_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 360, 150));

        centroid_pnl.setBackground(new java.awt.Color(0, 153, 153));
        centroid_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "[6] Centroid", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tf_centroid.setEditable(false);

        btn_centroid.setText("proses");
        btn_centroid.setEnabled(false);
        btn_centroid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_centroidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centroid_pnlLayout = new javax.swing.GroupLayout(centroid_pnl);
        centroid_pnl.setLayout(centroid_pnlLayout);
        centroid_pnlLayout.setHorizontalGroup(
            centroid_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centroid_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_centroid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_centroid, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        centroid_pnlLayout.setVerticalGroup(
            centroid_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centroid_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centroid_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_centroid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_centroid))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        proses_pnl.add(centroid_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 630, 360, 60));

        navbar_pnl.add(proses_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 700));

        getContentPane().add(navbar_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        // TODO add your handling code here:
        if(!tf_input1.getText().equals("")||!tf_input2.getText().equals("")){
            fuzzifikasi();
            operasi_fuzzy();
            implikasi();
            komposisi();
            model_tb_defuzzifikasi();
            btn_proses.setEnabled(false);
            btn_ok.setEnabled(true);
            btn_grafik.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "Isi Data Dengan Benar");
        }
    }//GEN-LAST:event_btn_prosesActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        try{
            clear_defuzzifikasi();
            defuzzifikasi();
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_centroidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_centroidActionPerformed
        // TODO add your handling code here:
        centroid();
        btn_centroid.setEnabled(false);
    }//GEN-LAST:event_btn_centroidActionPerformed

    private void btn_grafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grafikActionPerformed
        // TODO add your handling code here:
        grafik();
    }//GEN-LAST:event_btn_grafikActionPerformed

    private void tf_input1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_input1KeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
    }//GEN-LAST:event_tf_input1KeyTyped

    private void tf_input2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_input2KeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
    }//GEN-LAST:event_tf_input2KeyTyped

    private void fuzzifikasi(){
        String in1 = tb_data.getValueAt(0, 1).toString()+" "+tb_data.getValueAt(0, 2).toString();
        String in2 = tb_data.getValueAt(0, 1).toString()+" "+tb_data.getValueAt(0, 4).toString();
        String in3 = tb_data.getValueAt(1, 1).toString()+" "+tb_data.getValueAt(1, 2).toString();
        String in4 = tb_data.getValueAt(1, 1).toString()+" "+tb_data.getValueAt(1, 4).toString();

        lbl_f1.setText(in1);
        lbl_f2.setText(in2);
        lbl_f3.setText(in3);
        lbl_f4.setText(in4);

        input1 = Double.parseDouble(tf_input1.getText());
        input2 = Double.parseDouble(tf_input2.getText());
        min1 = Double.parseDouble(String.valueOf(tb_data.getValueAt(0, 3)));
        max1 = Double.parseDouble(String.valueOf(tb_data.getValueAt(0, 5)));
        min2 = Double.parseDouble(String.valueOf(tb_data.getValueAt(1, 3)));
        max2 = Double.parseDouble(String.valueOf(tb_data.getValueAt(1, 5)));

        hsl1 = (max1-input1)/(max1-min1);
        hsl2 = (input1-min1)/(max1-min1);
        hsl3 = (max2-input2)/(max2-min2);
        hsl4 = (input2-min2)/(max2-min2);

        tf_f1.setText(String.valueOf(hsl1));
        tf_f2.setText(String.valueOf(hsl2));
        tf_f3.setText(String.valueOf(hsl3));
        tf_f4.setText(String.valueOf(hsl4));
    }
    
    private void grafik(){
        DefaultTableModel mode = (DefaultTableModel) tb_data.getModel();
        int row = mode.getRowCount();
        
        for(int i=0;i<row;i++)
        {
            int ymax = Integer.parseInt(String.valueOf(tb_data.getValueAt(i, 5)));
            int ymin = Integer.parseInt(String.valueOf(tb_data.getValueAt(i, 3)));
            String lbl_max = String.valueOf(tb_data.getValueAt(i, 4));
            String lbl_min = String.valueOf(tb_data.getValueAt(i, 2));
            String lbl_y = String.valueOf(tb_data.getValueAt(i, 1));

            XYSeries xyMin = new XYSeries(lbl_min);
            xyMin.add(ymin,1);
            xyMin.add(ymax,0);

            XYSeries xyMax = new XYSeries(lbl_max);
            xyMax.add(ymax,1);
            xyMax.add(ymin,0);

            XYSeriesCollection dataset = new XYSeriesCollection();
            dataset.addSeries(xyMin);
            dataset.addSeries(xyMax);

            JFreeChart chart = ChartFactory.createXYLineChart("Grafik "+lbl_y, lbl_y, "", dataset);
            ChartFrame frame =new ChartFrame ("framechart",chart);
            frame.setVisible(true);
            frame.setBounds(500, 200, 500, 500);
        }
        
    }
    
    private void operasi_fuzzy(){
        min_hsl.add(Math.min(hsl1, hsl3));
        min_hsl.add(Math.min(hsl1, hsl4));
        min_hsl.add(Math.min(hsl2, hsl3));
        min_hsl.add(Math.min(hsl2, hsl4));
        
        DefaultTableModel mode = (DefaultTableModel) tb_operasi.getModel();
        for(int i=0; i<min_hsl.size(); i++)
        {
            String index = "[R"+(i+1)+"]";
            mode.addRow(new Object[]{
                index,
                min_hsl.get(i)
            });
        }
    }
    
    private void implikasi(){   
        DefaultTableModel mode = (DefaultTableModel) tb_implikasi.getModel();
        for(int i=0; i<min_hsl.size(); i++)
        {
            String index = "[R"+(i+1)+"]";
            mode.addRow(new Object[]{
                index,
                min_hsl.get(i),
                String.valueOf(tb_rules.getValueAt(i, 2))
            });
        }
    }
    
    private void komposisi(){
        DefaultTableModel mode = (DefaultTableModel) tb_komposisi.getModel();
        mode.addColumn(String.valueOf(tb_rules.getValueAt(1, 2)));
        mode.addColumn(String.valueOf(tb_rules.getValueAt(3, 2)));
        double r1 = Double.parseDouble(String.valueOf(tb_implikasi.getValueAt(0, 1)));
        double r2 = Double.parseDouble(String.valueOf(tb_implikasi.getValueAt(1, 1)));
        double r3 = Double.parseDouble(String.valueOf(tb_implikasi.getValueAt(2, 1)));
        double r4 = Double.parseDouble(String.valueOf(tb_implikasi.getValueAt(3, 1)));
        mode.addRow(new Object[]{
            Math.max(r1, r2),
            Math.max(r3, r4)
        });
    }
    
    class range_random{
        int randomWithRange(int min, int max){   //defining method for a random number generator
            int range = (max - min) + 1;     
            return (int)(Math.random() * range) + min;
        }
    }
    
    private void model_tb_defuzzifikasi(){
        DefaultTableModel mode = (DefaultTableModel) tb_defuzifikasi.getModel();
        
        mode.addColumn(String.valueOf(tb_rules.getValueAt(1, 2)));
        mode.addColumn(String.valueOf(tb_rules.getValueAt(3, 2)));
        
    }
    
    private void clear_defuzzifikasi(){
        DefaultTableModel mode = (DefaultTableModel) tb_defuzifikasi.getModel();
        int row = mode.getRowCount();
        for(int i=0;i<row;i++){
            mode.removeRow(0);
        }
        
    }
    
    private void defuzzifikasi(){
        range_random range = new range_random();
        DefaultTableModel mode = (DefaultTableModel) tb_defuzifikasi.getModel();
        
        int nilai = (int) spn_nilai.getValue();
        int min = Integer.parseInt(String.valueOf(tb_data.getValueAt(2, 3)));
        int max = Integer.parseInt(String.valueOf(tb_data.getValueAt(2, 5)));
        
        for(int i=0;i<nilai;i++)
        {
            mode.addRow(new Object[]{
                range.randomWithRange(min, max),
                range.randomWithRange(min, max)
            });    
        }
        
        if(nilai<=0){
            btn_centroid.setEnabled(false);
        }else{
            btn_centroid.setEnabled(true);
        }
    }
    
    private void centroid(){
        DefaultTableModel mode = (DefaultTableModel) tb_defuzifikasi.getModel();
        
        int row = mode.getRowCount();
        double total_kiri = 0;
        double total_kanan = 0;
        double komposisi_kiri = Double.parseDouble(String.valueOf(tb_komposisi.getValueAt(0, 0)));
        double komposisi_kanan = Double.parseDouble(String.valueOf(tb_komposisi.getValueAt(0, 1)));
        
        for(int i=0;i<row;i++){
            double kiri = Integer.parseInt(String.valueOf(tb_defuzifikasi.getValueAt(i, 0)));
            double kanan = Integer.parseInt(String.valueOf(tb_defuzifikasi.getValueAt(i, 1)));
            total_kiri += kiri;
            total_kanan += kanan;
        }
        
        double atas = (total_kiri * komposisi_kiri)+(total_kanan * komposisi_kanan);
        double bawah = (komposisi_kiri * Double.valueOf(row))+(komposisi_kanan * Double.valueOf(row));
        
        double centroid = atas/bawah;
        tf_centroid.setText(String.valueOf(centroid));
    }
    
    public static void tb_data(Object[] dataRow)
    {
        DefaultTableModel mode = (DefaultTableModel) tb_data.getModel();
        mode.addRow(dataRow);
    }
    
    public static void tb_aturan(Object[] dataRow)
    {
        DefaultTableModel mode = (DefaultTableModel) tb_rules.getModel();
        mode.addRow(dataRow);
    }
    
    void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_centroid;
    private javax.swing.JButton btn_grafik;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_proses;
    private javax.swing.JPanel centroid_pnl;
    private javax.swing.JPanel defuzzifikasi_pnl;
    private javax.swing.JPanel fuzzifikasi_pnl;
    private javax.swing.JPanel implikasi_pnl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel komposisi_pnl;
    public javax.swing.JLabel lbl_f1;
    public javax.swing.JLabel lbl_f2;
    public javax.swing.JLabel lbl_f3;
    public javax.swing.JLabel lbl_f4;
    public javax.swing.JLabel lbl_input1;
    public javax.swing.JLabel lbl_input2;
    private javax.swing.JPanel navbar_pnl;
    private javax.swing.JPanel operasi_pnl;
    private javax.swing.JPanel proses_pnl;
    private javax.swing.JPanel soal_pnl;
    private javax.swing.JSpinner spn_nilai;
    public static javax.swing.JTable tb_data;
    private static javax.swing.JTable tb_defuzifikasi;
    private static javax.swing.JTable tb_implikasi;
    private static javax.swing.JTable tb_komposisi;
    private static javax.swing.JTable tb_operasi;
    public static javax.swing.JTable tb_rules;
    private javax.swing.JTextField tf_centroid;
    private javax.swing.JTextField tf_f1;
    private javax.swing.JTextField tf_f2;
    private javax.swing.JTextField tf_f3;
    private javax.swing.JTextField tf_f4;
    private javax.swing.JTextField tf_input1;
    private javax.swing.JTextField tf_input2;
    private javax.swing.JPanel var_pnl;
    // End of variables declaration//GEN-END:variables
}
